hello

diff --git a/.github/workflows/second-art.yaml b/.github/workflows/second-art.yaml
--- a/.github/workflows/second-art.yaml
+++ b/.github/workflows/second-art.yaml
@@ -33,8 +33,14 @@ jobs:
         with:
           name: tweety-bird-text-file
 
-      - name: Test File Exists
-        run: grep -i "tweety-bird" tweety-bird.txt
+      - name: Test File Contents
+        run: |
+          if grep -qi "tweety-bird" tweety-bird.txt; then
+            echo "Tweety Bird found in file."
+          else
+            echo "Tweety Bird not found in file."
+            exit 1
+          fi
 
   deploy_artwork:
     runs-on: ubuntu-latest
@@ -50,3 +56,4 @@ jobs:
 
       - name: Deploy
         run: echo "Deploying..."
+
